# coupling matrix + Z0 + DC R을 조합해 net끼리의 coupling model을 SPICE .lib으로 export
"""Phase G-2 — coupling → SPICE netlist export.

F-1의 coupling matrix + Phase C의 Z0/Zdiff/DC R을 조합해 각 net을
lumped TL segment로, 각 coupled pair를 K coupling coefficient가
있는 mutual inductor로 표현한 SPICE lib을 생성. 사용자는 이걸
LTspice / ngspice에 로드해 crosstalk 시뮬 가능.

접근.
- 각 net → 단일 SUBCKT (L R C π모델, Z0 기반 R/C 근사)
- coupling pair → K_coupling 카드 (계수 = min(1, 1 - gap/coupling_ref))
- 모든 SUBCKT를 하나의 .lib 파일에 묶어 include-ready
"""

from __future__ import annotations

import math
from pathlib import Path
from typing import Any, Dict, List, Optional


# SPICE 표준 물리 상수 — 근사 coupling coefficient에만 사용.
_C0 = 2.998e8       # m/s
_MU0 = 4 * math.pi * 1e-7
_EPS0 = 8.854e-12


def _lumped_lc_from_z0(z0_ohm: float, length_mm: float,
                        er: float = 4.2) -> Dict[str, float]:
    """단일 net의 length + Z0에서 lumped L, C 도출.
    T = length / v_prop, v_prop = c0 / sqrt(er_eff)
    Z0 = sqrt(L/C), T = sqrt(LC)
    → L = Z0 * T, C = T / Z0"""
    if z0_ohm <= 0 or length_mm <= 0:
        return {'L_nH': 0.0, 'C_pF': 0.0, 'T_ps': 0.0}
    v_prop = _C0 / math.sqrt(er)
    T = (length_mm * 1e-3) / v_prop        # seconds
    L = z0_ohm * T                          # henries
    C = T / z0_ohm                          # farads
    return {'L_nH': L * 1e9, 'C_pF': C * 1e12, 'T_ps': T * 1e12}


def _coupling_k(coupling_length_mm: float, net_length_mm: float,
                 gap_mm: float = 0.30) -> float:
    """단순화된 coupling coefficient — 0 ≤ K < 1.
    Longer coupling relative to net length → larger K."""
    if net_length_mm <= 0:
        return 0.0
    fraction = max(0.0, min(1.0, coupling_length_mm / net_length_mm))
    # gap 0.3mm 기준 max K = 0.15 정도 (경험식)
    # (실 solver 결과와 다르지만 SPICE 시뮬 seed용)
    return round(0.15 * fraction, 4)


def build_spice_lib(result: Dict[str, Any], *,
                      subckt_prefix: str = 'NET_') -> str:
    """eval JSON 하나에서 SPICE library 텍스트 생성.

    Uses metrics.si.Z0_single_ended_ohm, metrics.si.branch_dc_resistance_mohm,
    metrics.coupling.top_pairs. Emits one SUBCKT per net + one K card
    per coupling pair.
    """
    metrics = result.get('metrics') or {}
    si = metrics.get('si') or {}
    coup = metrics.get('coupling') or {}
    z0 = si.get('Z0_single_ended_ohm') or {}
    dcr = si.get('branch_dc_resistance_mohm') or {}
    stub = si.get('via_stub_length_mm') or {}

    lines: List[str] = []
    lines.append('* Auto-generated by bga_router spice-export (Phase G-2)')
    lines.append(f"* Dataset: {result.get('dataset')}  BGA: {result.get('bga')}"
                  f"  Recipe: {result.get('recipe')}")
    lines.append('* Model: lumped RLC per net + K coupling per pair.')
    lines.append('*        Length estimated from Z0 + DC R.')
    lines.append('')

    def _net_length_mm(net: str) -> float:
        """Invert R = ρ*L/(w*t) with defaults w=0.075, t=0.035, ρ=1.68e-5."""
        r_mohm = dcr.get(net)
        if r_mohm is None:
            return 0.0
        r_ohm = r_mohm / 1000.0
        w = 0.075
        t = 0.035
        rho = 1.68e-5
        if rho <= 0:
            return 0.0
        return r_ohm * (w * t) / rho

    # One SUBCKT per net
    inductor_ids: Dict[str, str] = {}
    for net in sorted(z0):
        Z = z0.get(net, 0.0)
        L_mm = _net_length_mm(net)
        params = _lumped_lc_from_z0(Z, L_mm)
        sub_name = subckt_prefix + net
        lines.append(f'.SUBCKT {sub_name} in out gnd')
        # π-network: R/2 - L - R/2 in series, C/2 each to gnd.
        R_ohm = max(0.01, dcr.get(net, 0.0) / 1000.0)
        L_nH = params['L_nH']
        C_pF = params['C_pF']
        inductor_id = f'L{net}'
        inductor_ids[net] = inductor_id
        lines.append(f'  R1 in mid1 {R_ohm/2:.6g}')
        lines.append(f'  {inductor_id} mid1 mid2 {L_nH:.6g}nH')
        lines.append(f'  R2 mid2 out {R_ohm/2:.6g}')
        lines.append(f'  C1 in gnd {C_pF/2:.6g}pF')
        lines.append(f'  C2 out gnd {C_pF/2:.6g}pF')
        stub_mm = stub.get(net, 0.0)
        if stub_mm > 0:
            stub_L = _lumped_lc_from_z0(Z, stub_mm)['L_nH']
            lines.append(f'  Lstub in gnd {stub_L:.6g}nH  ; via stub')
        lines.append(f'.ENDS {sub_name}')
        lines.append('')

    # K coupling cards from coupling top_pairs
    top = coup.get('top_pairs') or []
    if top:
        lines.append('* Coupling coefficients (K cards)')
        for entry in top:
            pair = entry.get('pair') or []
            if len(pair) != 2:
                continue
            a, b = pair
            La = inductor_ids.get(a)
            Lb = inductor_ids.get(b)
            if La is None or Lb is None:
                continue
            length_mm_a = _net_length_mm(a)
            k = _coupling_k(entry.get('length_mm', 0.0), length_mm_a)
            lines.append(f'K_{a}_{b} {La} {Lb} {k}')
        lines.append('')

    lines.append(f'* {len(inductor_ids)} net models emitted, '
                  f'{len(top)} coupling cards')
    return '\n'.join(lines)


def write_spice_lib(result_path: str | Path, out_path: str | Path,
                      *, subckt_prefix: str = 'NET_') -> Path:
    """Read a route JSON, write a SPICE .lib file, return the Path."""
    import json as _json
    r = _json.loads(Path(result_path).read_text())
    text = build_spice_lib(r, subckt_prefix=subckt_prefix)
    op = Path(out_path)
    op.parent.mkdir(parents=True, exist_ok=True)
    op.write_text(text)
    return op
