if(EXISTS "/home/koopark/claude/KooSimulationDataReader/build-phase5/tests/koo_mesh_tests[1]_tests.cmake")
  include("/home/koopark/claude/KooSimulationDataReader/build-phase5/tests/koo_mesh_tests[1]_tests.cmake")
else()
  add_test(koo_mesh_tests_NOT_BUILT koo_mesh_tests_NOT_BUILT)
endif()
